---
services:
  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - ./.data/grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"

  timescale:
    image: docker.io/timescale/timescaledb:2.17.2-pg17
    restart: unless-stopped
    volumes:
      - ./.data/timescale:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_PASSWORD=itgain
      - TS_TUNE_MAX_CONNS=100
      - TS_TUNE_MEMORY=4GB
      - TS_TUNE_NUM_CPUS=2
    command: postgres -c 'lock_timeout=900000' -c shared_preload_libraries=timescaledb,pg_stat_statements -c pg_stat_statements.track=all -c 'dynamic_shared_memory_type=sysv' -c max_connections=100 -c max_locks_per_transaction=256 -c track_io_timing=true

  grafana7:
    image: grafana/grafana-oss:7.5.10
    volumes:
      - ./.data/grafana7:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3007:3000"