{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Backends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select $__timeGroup(\"time\", '$__interval') \nas time,\ndatname,\ndatid::text,\nmax(numbackends) as numbackends\nfrom observability.hist_pg_stat_database\nwhere $__timeFilter(\"time\")\ngroup by 1,2,3 order by 1"
    }
   ]
  },
  {
   "title": "blks_read_per_sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  datname as metric,\n  (CASE WHEN avg(blks_read) >= lag(avg(blks_read)) OVER (PARTITION BY datname ORDER BY $__timeGroup(\"time\",$__interval)) THEN avg(blks_read) - lag(avg(blks_read)) OVER (PARTITION BY datname ORDER BY $__timeGroup(\"time\",$__interval)) WHEN lag(avg(blks_read)) OVER (PARTITION BY datname ORDER BY $__timeGroup(\"time\",$__interval)) IS NULL THEN NULL ELSE avg(blks_read) END)/extract(epoch from min(\"time\") - lag(min(\"time\")) OVER (PARTITION BY datname ORDER BY $__timeGroup(\"time\",$__interval))) AS \"blks_read\"\nFROM observability.hist_pg_stat_database\nWHERE\n  $__timeFilter(\"time\") AND\n  datname is not null\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Backends first (15m buckets)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select $__timeGroup(\"time\", '$__interval') \nas time,\ndatname,\ndatid::text,\nfirst(numbackends,\"time\") as numbackends\nfrom observability.hist_pg_stat_database\nwhere $__timeFilter(\"time\")\ngroup by 1,2,3 order by 1"
    }
   ]
  },
  {
   "title": "blks_read_per_sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  datname as metric,\n  (CASE WHEN avg(blks_read) >= lag(avg(blks_read)) OVER (PARTITION BY datname ORDER BY $__timeGroup(\"time\",$__interval)) THEN avg(blks_read) - lag(avg(blks_read)) OVER (PARTITION BY datname ORDER BY $__timeGroup(\"time\",$__interval)) WHEN lag(avg(blks_read)) OVER (PARTITION BY datname ORDER BY $__timeGroup(\"time\",$__interval)) IS NULL THEN NULL ELSE avg(blks_read) END)/extract(epoch from min(\"time\") - lag(min(\"time\")) OVER (PARTITION BY datname ORDER BY $__timeGroup(\"time\",$__interval))) AS \"blks_read\"\nFROM observability.hist_pg_stat_database\nWHERE\n  $__timeFilter(\"time\") AND\n  datname is not null\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}