{
 "title": "Workshop Result",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSourceVariable", "label": "PDB", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage Overall",
   "type": "timeseries",
   "description": "Total CPU Usage. Stacked Trendchart. 100% means 100% overall all cores available",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(snapshot_time,$__interval),\n  hostname,\n  1 - (CASE WHEN max(val4) >= lag(max(val4)) OVER (PARTITION BY entity ORDER BY $__timeGroup(snapshot_time,$__interval)) THEN max(val4) - lag(max(val4)) OVER (PARTITION BY entity ORDER BY $__timeGroup(snapshot_time,$__interval)) WHEN lag(max(val4)) OVER (PARTITION BY entity ORDER BY $__timeGroup(snapshot_time,$__interval)) IS NULL THEN NULL ELSE max(val4) END)/cast (\n    CASE\n      WHEN max(val1 + val2 + val3 + val4 + val5 + val6 + val7) >= lag(max(val1 + val2 + val3 + val4 + val5 + val6 + val7)) OVER (\n        PARTITION BY entity\n        ORDER BY\n          $__timeGroup(snapshot_time,$__interval)\n      ) THEN max(val1 + val2 + val3 + val4 + val5 + val6 + val7) - lag(max(val1 + val2 + val3 + val4 + val5 + val6 + val7)) OVER (\n        PARTITION BY entity\n        ORDER BY\n          $__timeGroup(snapshot_time,$__interval)\n      )\n      WHEN lag(max(val1 + val2 + val3 + val4 + val5 + val6 + val7)) OVER (\n        PARTITION BY entity\n        ORDER BY\n          $__timeGroup(snapshot_time,$__interval)\n      ) IS NULL THEN NULL\n      ELSE max(val1 + val2 + val3 + val4 + val5 + val6 + val7)\n    END\n  as decimal ) AS \"cpu_utilization_pct\"\nFROM spg_mon_os.v_proc_stat\nWHERE\n  $__timeFilter(snapshot_time) AND\n  entity LIKE 'cpu'\nGROUP BY 1,hostname, entity\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Systemload",
   "type": "timeseries",
   "description": "system load averages; short->1min, mid->5min, long->15min\nRed dotted line is number of cores",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(snapshot_time,$__interval),\n  hostname,\n  max(load5) AS \"load5\"\nFROM spg_mon_os.v_proc_loadavg\nWHERE\n  $__timeFilter(snapshot_time)\nGROUP BY 1,hostname\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Time per Read per disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(snapshot_time,$__interval),\n  hostname,device,\n  ((CASE WHEN avg(time_spent_reading_ms) >= lag(avg(time_spent_reading_ms)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) THEN avg(time_spent_reading_ms) - lag(avg(time_spent_reading_ms)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) WHEN lag(avg(time_spent_reading_ms)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) IS NULL THEN NULL ELSE avg(time_spent_reading_ms) END)/extract(epoch from min(snapshot_time) - lag(min(snapshot_time)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)))) --AS \"time_spent_reading_ms\",\n  /\n  ((CASE WHEN avg(reads_total) > lag(avg(reads_total)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) THEN avg(reads_total) - lag(avg(reads_total)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) WHEN lag(avg(reads_total)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) IS NULL THEN NULL ELSE NULL END)/extract(epoch from min(snapshot_time) - lag(min(snapshot_time)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)))) --AS \"reads_total\",\n  as time_per_read\nFROM spg_mon_os.v_proc_diskstats\nWHERE\n  $__timeFilter(snapshot_time)\n  and time_spent_doing_io_ms > 0\nGROUP BY 1,2,3,display_name\nORDER BY 1,2,3"
    }
   ]
  },
  {
   "title": "Time per Write per disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(snapshot_time,$__interval),\n  hostname,device,\n  ((CASE WHEN avg(time_spent_writing_ms) >= lag(avg(time_spent_writing_ms)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) THEN avg(time_spent_writing_ms) - lag(avg(time_spent_writing_ms)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) WHEN lag(avg(time_spent_writing_ms)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) IS NULL THEN NULL ELSE avg(time_spent_writing_ms) END)/extract(epoch from min(snapshot_time) - lag(min(snapshot_time)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)))) --AS \"time_spent_writing_ms\",\n  /\n  ((CASE WHEN avg(writes_compl) > lag(avg(writes_compl)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) THEN avg(writes_compl) - lag(avg(writes_compl)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) WHEN lag(avg(writes_compl)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)) IS NULL THEN NULL ELSE NULL END)/extract(epoch from min(snapshot_time) - lag(min(snapshot_time)) OVER (PARTITION BY display_name,device ORDER BY $__timeGroup(snapshot_time,$__interval)))) --AS \"writes_compl\"\n  as time_per_write\nFROM spg_mon_os.v_proc_diskstats\nWHERE\n  $__timeFilter(snapshot_time)\n  and time_spent_doing_io_ms > 0\nGROUP BY 1,2,3,display_name\nORDER BY 1,2,3"
    }
   ]
  },
  {
   "title": "Blocks Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with delta as (\n  SELECT\n  $__timeGroupAlias(snapshot_time,$__interval),\n  display_name,hostname,datname,\n  (CASE WHEN max(blks_read) >= lag(max(blks_read)) OVER (order by $__timeGroup(snapshot_time,$__interval)) THEN max(blks_read) - lag(max(blks_read)) OVER (order by $__timeGroup(snapshot_time,$__interval)) WHEN lag(max(blks_read)) OVER (order by $__timeGroup(snapshot_time,$__interval)) IS NULL THEN NULL ELSE max(blks_read) END)/extract(epoch from min(snapshot_time) - lag(min(snapshot_time)) OVER (order by $__timeGroup(snapshot_time,$__interval))) AS \"blks_read\",\n  (CASE WHEN max(blks_hit) >= lag(max(blks_hit)) OVER (order by $__timeGroup(snapshot_time,$__interval)) THEN max(blks_hit) - lag(max(blks_hit)) OVER (order by $__timeGroup(snapshot_time,$__interval)) WHEN lag(max(blks_hit)) OVER (order by $__timeGroup(snapshot_time,$__interval)) IS NULL THEN NULL ELSE max(blks_hit) END)/extract(epoch from min(snapshot_time) - lag(min(snapshot_time)) OVER (order by $__timeGroup(snapshot_time,$__interval))) AS \"blks_hit\"\n  FROM spg_mon_pg.v_pg_stat_database\n  WHERE\n  $__timeFilter(snapshot_time)\n  GROUP BY 1,2,3,4\n)\nselect time,display_name,hostname,datname,blks_hit/(blks_hit+blks_read) as blks_hit_ratio from delta\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(snapshot_time,$__interval),\n  display_name,hostname,datname,\n  max(numbackends) AS \"numbackends\"\nFROM spg_mon_pg.v_pg_stat_database\nWHERE\n  $__timeFilter(snapshot_time)\nGROUP BY 1,display_name,hostname,datname\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "TUP Inserted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(snapshot_time,$__interval),\n  display_name,hostname,datname,\n(CASE WHEN max(tup_inserted) >= lag(max(tup_inserted)) OVER (PARTITION BY display_name ORDER BY $__timeGroup(snapshot_time,$__interval)) THEN max(tup_inserted) - lag(max(tup_inserted)) OVER (PARTITION BY display_name ORDER BY $__timeGroup(snapshot_time,$__interval)) WHEN lag(max(tup_inserted)) OVER (PARTITION BY display_name ORDER BY $__timeGroup(snapshot_time,$__interval)) IS NULL THEN NULL ELSE max(tup_inserted) END)/extract(epoch from min(snapshot_time) - lag(min(snapshot_time)) OVER (PARTITION BY display_name ORDER BY $__timeGroup(snapshot_time,$__interval))) AS \"tup_inserted\"\nFROM spg_mon_pg.v_pg_stat_database\nWHERE\n  $__timeFilter(snapshot_time) \nGROUP BY 1,display_name,hostname,datname\nORDER BY 1"
    }
   ]
  },
  {
   "title": "TUP returned",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(snapshot_time,$__interval),\n  display_name,hostname,datname,\n(CASE WHEN max(tup_returned) >= lag(max(tup_returned)) OVER (PARTITION BY display_name ORDER BY $__timeGroup(snapshot_time,$__interval)) THEN max(tup_returned) - lag(max(tup_returned)) OVER (PARTITION BY display_name ORDER BY $__timeGroup(snapshot_time,$__interval)) WHEN lag(max(tup_returned)) OVER (PARTITION BY display_name ORDER BY $__timeGroup(snapshot_time,$__interval)) IS NULL THEN NULL ELSE max(tup_returned) END)/extract(epoch from min(snapshot_time) - lag(min(snapshot_time)) OVER (PARTITION BY display_name ORDER BY $__timeGroup(snapshot_time,$__interval))) AS \"tup_returned\"\nFROM spg_mon_pg.v_pg_stat_database\nWHERE\n  $__timeFilter(snapshot_time) \nGROUP BY 1,display_name,hostname,datname\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Lock Contentions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "select\r\ntime_bucket_gapfill('$__interval',snapshot_time) as time,\r\nhostname,dbname,\r\ncount(distinct blocked_pid::text || blocking_pid::text) \r\nas num_lock_contentions\r\nfrom spg_mon_pg.v_pg_mon_lockwaits\r\nwhere\r\n  $__timeFilter(snapshot_time) and\r\n\tdatname is not null \r\n  group by 1,2,3"
    }
   ]
  },
  {
   "title": "Queries Slower 1s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "with delta as (\r\n  select snapshot_time,display_name,dbname,queryid,\r\n    case when calls > lag(calls) over (partition by display_name,dbname,queryid order by snapshot_time) then\r\n      mean_exec_time\r\n      else null\r\n    end as mean_exec_time\r\n  from spg_mon_pg.v_pg_stat_statements\r\n  where\r\n    $__timeFilter(snapshot_time) and\r\n    datname is not null \r\n    and mean_exec_time > 1000\r\n) select\r\ntime_bucket_gapfill('$__interval',snapshot_time) as time,\r\ndisplay_name,dbname,\r\nlocf(count(distinct queryid)) as num_querie_slow_1s \r\nfrom delta\r\nwhere $__timeFilter(snapshot_time)\r\ngroup by 1,2,3\r\norder by 1"
    }
   ]
  }
 ]
}